version: '3'
services:
  grworker1:
    build: ./worker
    container_name: grworker1
    volumes:
      - /home/paraujo/GRPC/dataset:/workspace/dataset
    environment:
      - RANK=0
      - WORLD_SIZE=2
      - MASTER_ADDR=grworker1
      - MASTER_PORT=8888
      - NCCL_DEBUG=INFO
      - API_HOST=grserver
      - API_PORT=8040
    tty: true  
    stdin_open: true
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  grworker2:
    build: ./worker
    container_name: grworker2
    volumes:
      - /home/paraujo/GRPC/dataset:/workspace/dataset
    environment:
      - RANK=1
      - WORLD_SIZE=2
      - MASTER_ADDR=grworker1
      - MASTER_PORT=8888
      - NCCL_DEBUG=INFO
      - API_HOST=grserver
      - API_PORT=8040
    tty: true
    stdin_open: true
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  grserver:
    build: ./server
    environment:
      - NODES = 2
      - BATCH_SIZE = 64
      - NUM_CLASSES = 10
    container_name: grserver
    volumes:
      - /home/paraujo/GRPC/dataset:/workspace/dataset
    ports:
      - "8040:8040"
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge